### ISSUE TITLE
MQGMO, MQPMO

### ISSUE THREAD

**Issue by fjbsaper** [ibm-messaging/mq-mqi-nodejs#1]
Looked at your setup and did not see the fail if quiesce option being put as a standard.
Should it be added into the default for the js setup?

**Comment by ibmmqmet** [comment]
The defaults - at least for now - are the same as the other MQI implementations. I did consider changing some of the defaults for a few of the fields, including these. But given that the normal way of applications setting the flags overrides those defaults (you nearly always will be setting some other MQPMO or GMO option anyway), having a different default might not be worth doing. Of course, I could instead always FORCE the value into the option fields. I think I might prefer doing that, as there's very rarely a need not to have the FIQ option set.

And for completeness, there could in theory be a different approach to setting them. Rather than adding bitfield values into an integer,  consider the external datatype being a collection such as a set with separate entries for each bit, and then I could extract all the elements and do the calculations - pre-filling a set with default values would make it possible to clear it if absolutely necessary. That takes the interface further away from what people know today, but may have other advantages.

Any thoughts? 
* Leave defaults as is
* Leave defaults as it, but then force the option on
* Have a set instead of a number

I'm leaning towards a preference for the second option, but not going to do anything immediate about it.

**Comment by fjbsaper** [comment]
I'd have thought just to prefill it. For most implementations when it is a fast and loose, the options (gmo, pmo) are taken as is an not changed. If you're changing them I'd expect you to know what you're doing and add the different options as needed.
The force FIQ on is also a good strategy. Don't know if we should allow an override i.e. not force on in rare case where FIQ is not desired.
I understand the default on the MQI does not set FIQ. I consider this to be an (oops we should have) case.

**Comment by ibmmqmet** [comment]
Decided to both change defaults and force FIQ anyway.
