### ISSUE TITLE
Cannot resolve error - MQ call failed in CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_CNO_ERROR [2139]

### ISSUE THREAD

**Issue by brendon-flanagan** [ibm-messaging/mq-mqi-nodejs#103]
Trying to do a client connection from rhel7 to mq server on windows.   version of mq is v8.0.0.2

This is by using the sample amqsconn.js script and only changing the cd.ConnectionName to the ip address and port of the server.   Also changing to the right qmgr, though should by rights connect as default anyway.

MQ client details.

crtmqm is not in the bin folder thus client installed.

Name:        IBM MQ
Version:     9.0.5.0
Level:       p905-L180305.1
BuildType:   IKAP - (Production)
Platform:    IBM MQ for Linux (x86-64 platform)
Mode:        64-bit
O/S:         Linux 3.10.0-1127.13.1.el7.x86_64
InstName:    Installation1
InstDesc:
Primary:     No
InstPath:    /opt/mqm
DataPath:    /var/mqm
MaxCmdLevel: 905

**Comment by ibmmqmet** [comment]
The amqsconn program tries to set the ApplName in the CNO which was a feature added in 9.1.2. If the NodeJS package is referencing your 9.0.5 installed client instead of an automatically-downloaded install (which is currently 9.2.0), then 9.0.5 doesn't support that option. So the client side will reject the CNO.

And the qmgr in any case is even older. So it might be getting rejected there.

Comment out the line that sets the ApplName.

**Comment by brendon-flanagan** [comment]
Yep, commented out and worked.    Auto install of client mq didn't work, it wouldn't find it for whatever reason, and had to manually download a package from ibm download centre instead for which I just chose not the latest just in case of any bugs.
