### ISSUE TITLE
Getting error after updating to 0.9.16 from 0.9.14

### ISSUE THREAD

**Issue by MansharamaniRahul** [ibm-messaging/mq-mqi-nodejs#107]
I am getting the below error while connecting to Q_Manager after I updated the version from 0.9.14 to 0.9.16. Below is the sample code

  var mq = require("ibmmq");
  var cd = new mq.MQCD();
  cd.ConnectionName = `XYZ(1414)`;
  cd.ChannelName = XYZ_CHANNEL;
  cno.ClientConn = cd;

 mq.Connx(qManagerLocal, cno,function (err,conn){
if(err)
console.log(err)
else
console.log('successful connection');
})

Error---->{"name":"MQError","message":"CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_Q_MGR_NAME_ERROR [2058]","mqcc":2,"mqccstr":"MQCC_FAILED","mqrc":2058,"mqrcstr":"MQRC_Q_MGR_NAME_ERROR","version":"0.9.16","verb":"CONNX"}

I am trying to connect to IBM MQ on a separate server using VPN network. This was working fine with previous version (0.9.14)

**Comment by ibmmqmet** [comment]
Assuming that the channel name etc are accurate, the most common reason for getting a 2058 return code is that the MQ code is trying to connect to a qmgr on the same machine using local bindings instead of as a client. Which might be caused by a number of things, depending on what you've actually got installed on your system - for example the app might be trying to use a version of MQ code installed in /opt/mqm instead of under the `node_modules` tree. 

You don't show code that actually creates the cno variable, but one way to force a client connection is to set `cno.Options |= mq.MQCNO_CLIENT_BINDING`

**Comment by ibmmqmet** [comment]
closing as no further diagnostics or updates
