### ISSUE TITLE
Environment Issue while connection to the queue

### ISSUE THREAD

**Issue by prabhatmishra33** [ibm-messaging/mq-mqi-nodejs#112]
Dear Team,

I am getting below issue when i am trying to create a connection with the queue servers. Roughly before 1 week, it was working fine, now this issue.

`MQError: CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_ENVIRONMENT_ERROR [2012]
    at <project-path>/node_modules/ibmmq/lib/mqi.js:776:17
    at Object.<anonymous> (<<project-path>>/node_modules/ffi-napi/lib/_foreign_function.js:115:9) {
  mqcc: 2,
  mqccstr: 'MQCC_FAILED',
  mqrc: 2012,
  mqrcstr: 'MQRC_ENVIRONMENT_ERROR',
  version: '0.9.16',
  verb: 'CONNX'
}`

Could you please help me in this ?

**Comment by ibmmqmet** [comment]
And what has changed in your system in the last week?

**Comment by prabhatmishra33** [comment]
I have installed a new Mac Os, Moved to Mojave  Os
After that, I did the same setup which was working for me previously for ibmmq.
https://github.com/ibm-messaging/mq-mqi-nodejs/issues/87#issuecomment-696676842
Then it started working but again facing an issue :(

**Comment by ibmmqmet** [comment]
The only time I've seen MQRC_ENVIRONMENT_ERROR in this kind of situation is when the MQ client code has not been correctly installed or when there were multiple different versions of it being pointed at by the LD_LIBRARY_PATH or equivalent. See https://github.com/ibm-messaging/mq-golang/issues/124 for a similar situation - that's Go rather than Node but both end up going to the same C libraries.

**Comment by chughts** [comment]
I think you may be using an old MQ Toolkit for Mac. For Mac OS Mojave and Big Sur, all installed executables, DLLs and packages need to be signed. 

You will need to download and install the signed MQ Toolkit for Mac - https://ibm.biz/mqdevmacclient

**Comment by ibmmqmet** [comment]
Closing as no additional info or diagnostics
