### ISSUE TITLE
Question regarding multiprocessing

### ISSUE THREAD

**Issue by mortenLom** [ibm-messaging/mq-mqi-nodejs#19]
Hi
This may be trivial for some people, but it's not clear to me. I'll be happy for any help. It has to do with multiprocessing.
I am writing a web application using node.js and ibmmq. The web application will expose a REST API that clients can call. The typical scenario is: 
1. A client sends a http request to my web application. 
2. My web application will receive the request, interprete it and then send a message to a MQ queue on another machine.
3. Then my web application will read asynchronously from another MQ queue (same queue handler)
(at this moment the Node.js stack is free to handle other things, so typically it can handle another http request from another client)
4. Then the callback function of step 3 is triggered. It reads the message from the MQ queue and sends a response to the client in step 1.

My question is. In Step 3 I need to do a MQCONN and MQOPEN. Do I leave this open&connected or do I close&disconnect after handling the request? I'm thinking, if I close&disconnect I may destroy for another client? So I would think I should leave it open&connected as long as my web application is running. Is this correct?

Morten

**Comment by ibmmqmet** [comment]
I would normally expect a program [process] to connect and hold resources open as long as possible. You will have connected in step 2, but there's no reason to connect a second time in 3. Similarly, you will have had to open the reply queue in order to set up the async callback to receive the message; that queue handle should be left open if you expect to use that same queue again, Unless you have various security requirements (eg each client is authenticating independently to the queue manager, with your web app just passing through the credentials), a single connection can be used for all clients.
