### ISSUE TITLE
Deploying to BlueMix

### ISSUE THREAD

**Issue by scarified** [ibm-messaging/mq-mqi-nodejs#28]
I am enjoying the mq-mqi-nodejs library. However, I am having trouble getting a node.js app that runs perfectly fine on my Windows laptop to deploy and run on Bluemix.

cf push test 

produces this error ... 

[APP/PROC/WEB/0] ERR Error: ENOENT: no such file or directory, open 'libmqm_r.so'

Any help would be appreciated !

**Comment by ibmmqmet** [comment]
I assume that you've already got the MQ C client code installed on the image, so libmqm_r does exist somewhere. Then you may need to have run [setmqenv](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.ref.adm.doc/q083560_.htm) so that the LD_LIBRARY_PATH env var is correctly set to point to where MQ is installed.

I'm considering trying to search a couple of explicit places if the lib cannot be loaded implicitly - eg always try /opt/mqm/lib for Linux, so it could work even if you haven't run setmqenv - but I need to test whether that actually works as libmqm in turn does need to load dependent libraries under it and I know it does some "interesting" things under the covers.

**Comment by scarified** [comment]
That's the problem. I had assumed that the MQ C client code was part of the mq-mqi-nodejs module (that the module was self contained). Thank you.
