### ISSUE TITLE
no AMQSPUB

### ISSUE THREAD

**Issue by ChrisPhillips-cminion** [ibm-messaging/mq-mqi-nodejs#32]
There is no sample for amqspub.

I tried modifying amqsput to change the object type to a topic, but to no avail. It says it is successful but i am unable to retrieve the message from the topic.

**Comment by ibmmqmet** [comment]
You might need to change the put program so that it does
   
    od.ObjectString = qName  // actually the topic, but that requires changing variable name!
    od.ObjectType = MQC.MQOT_TOPIC

instead of

    od.ObjectName = qName
    od.ObjectType = MQC.MQOT_Q

This is because of the relationship between topic strings and topic objects - see [here](https://www.ibm.com/developerworks/community/blogs/messaging/entry/mq_topics_but_which_type?lang=en) for some further explanation of that. The amqssub program uses the ObjectString only, and the publishers and subscribers need to agree on the overall topic formed by the combination of objectName and objectString.

**Comment by ibmmqmet** [comment]
I just added an amqspub sample that matches the changes I described above (though I also changed the variable names to match). And a "pubsub" script to drive it.

**Comment by ChrisPhillips-cminion** [comment]
Thanks its working now.
