### ISSUE TITLE
Example for using CCDT

### ISSUE THREAD

**Issue by orweinberger** [ibm-messaging/mq-mqi-nodejs#41]
I'm trying to get the `amqsconn.js` sample to work with a CCDT file. From the README I can see that I need to set the correct environment variables, but it doesn't seem to have any affect. I'm setting `MQCHLLIB` and `MQCHLTAB` but cannot get this to work.

Is it possible to provide a very quick snippet on how to use `amqsconn.js` with a CCDT file?

**Comment by ibmmqmet** [comment]
What is actually happening when you set those variables? Are they set correctly? Is the CCDT readable in that location by the application? Anything in error logs on the client or qmgr? 

Have you realised that the amqsconn.js sample is demonstrating how to explicitly set the connection information in the code. To change that, delete the line "cno.ClientConn=cd". The amqsput sample should work unchanged.

The [KnowledgeCentre](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.con.doc/q016770_.html) has examples of setting the variables. This NodeJS package doesn't do anything special here; the underlying C library does the work.

Sometimes, depending on what else I have installed in the system, I also set the enviroment **MQ_CONNECT_TYPE=CLIENT** to force the connection to that mode, rather than attempt a local binding. And for deep debug, to verify which file is actually being read, I've occasionally run a client program under **strace** and look at the output from that.

If I've copied the CCDT to the local directory where my app is running, then the settings would be

~~~
  export MQCHLLIB=.
  export MQCHLTAB=AMQCLCHL.TAB
  export MQ_CONNECT_TYPE=CLIENT   (optional)
~~~
