### ISSUE TITLE
Message Acknowledgement?

### ISSUE THREAD

**Issue by newhouse** [ibm-messaging/mq-mqi-nodejs#52]
Thanks for the great library!

I'm wondering if there's an example of how to do message acknowledgement with this using a 9.1.x MQ Client? I'd like to make sure that messages are re-processed if something goes wrong between when they're read off the queue and when the processor is done with them.

**Comment by ibmmqmet** [comment]
I'm not certain exactly what you mean by message acknowledgement, but the usual mechanism for reliable processing is to use transactions - MQPMO_SYNCPOINT/MQGMO_SYNCPOINT options for put/get of as many messages as you need, followed by Cmit() to commit the changes. Any failure before the commit point will automatically roll back the changes.

Single-phase commit (where MQ is the only resource involved) is discussed in detail at https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.dev.doc/q026800_.htm

**Comment by newhouse** [comment]
Yes, this is what I’m talking about (in other systems I’ve used the idea is called acknowledging or deleting). 

Thanks for these pointers and your comment! I actually found this approach and experimented with it yesterday. I found that while using Async Get with Syncpoints my app might have more than 1 message “in flight” (being processed) at a time, and a Commit call being made in any one of their callbacks would cause all of them to be committed. This could lead to data being lost if there was a problem with any of the in-flight messages after the commit. I ended up changing my code to use GetSync with NO WAIT so commits are isolated but my app cannot process messages concurrently with a single queue manager. 

Does that all sound correct to you or is there anything I am missing or could be doing better?

**Comment by ibmmqmet** [comment]
I'm a bit surprised that you are seeing multiple messages in-flight. Is your message callback function given to Get() a "synchronous" operation or is it in turn scheduling some other async work to actually deal with the message. Once the callback has completed, then another message can be delivered so a too-early apparent completion may loop faster than the real work.

Cmit() deliberately does have the scope of the qmgr connection, so that all uncommitted work, potentially across multiple queues (frequently a GET followed by a PUT reply to a different queue) is handled in one UoW.

Certainly using a synch get makes the flow clearer so that might be a simpler design, but then you have to be careful about polling too fast on the GET/NO-WAIT. You might also consider using GetDone() in your callback function which should stop another message being delivered until you next call Get() to kick off another async message delivery.

**Comment by newhouse** [comment]
Thanks! I did get from your documentation that next Get is performed after the callbcack function returns, but (as you guessed) my callback does some things which are asynchrous and basically returns an unhandled Promise immediately. 

I wonder how hard it would be for the library to either [
a) (preferred style) check and then wait for a Promise (if one was returned) returned from the callback to resolve
b) provide another callback as a param to the callback that can be called when work is complete
] before another iteration on the same queue manager is executed?

Finally, what is the danger with polling too often on a get/no-wait? That the event loop will be held up all the time by the blocking GetSyncs?  Is there an advantage to still doing async Get, immediately calling GetDone and then calling Get again at the end vs creating my own looping structure with GetSync?  In my current implementation I do as I saw in the internals: If I encountered a message on this loop, I call GetSync again immediately. Otherwise I delay a bit (500ms) before calling the loop again. Maybe the advantage of your suggestion is not having to write and maintain all that?

Thanks!

**Comment by ibmmqmet** [comment]
Main issues about polling too often are a) CPU use particularly on the server where it might be affecting other apps and b) potentially blocking other work in your program. That's why there's the current design of timers etc. Obviously you can copy/adapt that code to a specific pattern based around the GetSync() that matches your use case but then you have to maintain it.

I am concerned about there being several different techniques that could be used to indicate completion of the callback as this code tries to be as general-purpose as possible. That's one reason I've tried to avoid Promises and other approaches explicitly in the API, as it should be relatively easy for someone to do that in their own code before completing what I see as the callback. They can choose a style that matches their application style. But if Promises turn out to be the mechanism that (nearly) everyone wants to use for this kind of operation then I would consider adding it to the library in future.

**Comment by newhouse** [comment]
Thanks again for your comments and suggestions. 

So just to be clear: there is not currently a way to delay the moment of when ibmmq considers a callback as having completed if that callback is doing something asynchronous, correct? I can think of no pattern or trick myself that won’t result in an “early” return of something (undefined, Promise, etc) in that case...and so either [an async Get with GetDones] or [GetSync with manual loop call] would be required to accomplish what I’m after? I can totally live with that but wanted to be sure!

Thanks again

**Comment by ibmmqmet** [comment]
Correct. There's probably something possible using a mutex locking strategy (perhaps https://www.npmjs.com/package/locks ) but I've not tried that.

**Comment by newhouse** [comment]
OK, great.  Maybe you want to leave this issue open for others to find, but as far as I'm concerned this issue is "closed".

Thanks again for all of your work on this library!
