### ISSUE TITLE
Not able to set MQMD Format

### ISSUE THREAD

**Issue by rohitjain31** [ibm-messaging/mq-mqi-nodejs#66]
Hi, I am using v0.9.2, and trying to change MQMD Format to "MQHRF2" while put message.
 
var mqmd = new mq.MQMD();
mqmd.Format = MQC.MQFMT_RF_HEADER_2;

message is published successfully via Put call, but while browsing messages i am getting "MQSTR" in Format field.

Please let me know if i miss anything.

**Comment by ibmmqmet** [comment]
Depending on how the message is retrieved, or the queue attributes, a message may be presented either with an RFH2 structure, or without - with the contents of the RFH2 instead being available as message properties. Using MQGMO_PROPERTIES_AS_RFH2 as part of the Get will force the RFH2 to be visible.

**Comment by rohitjain31** [comment]
Hi, I tried "MQGMO_PROPERTIES_AS_RFH2" as part of Get, but still getting "MQSTR" in Format field of mqmd.
gmo.Options = MQC.MQGMO_BROWSE_NEXT | MQC.MQGMO_PROPERTIES_AS_MQRFH2 | MQC.MQGMO_NO_WAIT | MQC.MQGMO_FAIL_IF_QUIESCING;

i found "MQGMO_PROPERTIES_FORCE_MQRFH2" in IBM documentation (https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.ref.dev.doc/q008240_.htm) and used the same but still the same output.

mqmd output:
![image](https://user-images.githubusercontent.com/14266765/62197523-9b678180-b39d-11e9-9b5d-d810497f6732.png)

**Comment by ibmmqmet** [comment]
What are you putting to the queue? Have you correctly built the RFH2 contents at the start of the message? If so, then the message body should not be a string, but a byte buffer. (The RFH2 structure will contain non-character values.)

The code checks the type of the buffer, and will set it to a string if the input appears to be a string. Just setting the format to RFH2 won't create an RFH2 structure.

**Comment by rohitjain31** [comment]
didn't quite understand what you meant by building the RFH2 contents ?
I'm building a front end application in Angular which will give user the capability to choose message format b/w "MQSTR" and "MQRFH2", and then user can type a message and they can submit that.

Node js part, i am connecting to MQ in client mode and converted message to byte Buffer as suggested and set the mqmd.Format = MQC.MQFMT_RF_HEADER_2.

Any documentation around it will help me. Thanks.

**Comment by ibmmqmet** [comment]
The RFH2 header structure is defined here: https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.dev.doc/q099240_.htm The fixed header itself is followed by the XML-like body of name/value pairs before you get to the rest of the message body.

It's not just a matter of setting the MQMD Format field; the RFH2 structure - which is one way of setting additional message properties, most commonly seen as generated by MQ JMS programs - then has to follow with appropriate contents. And because the structure contains numbers as well as text component, it has to be treated as a byte array.

**Comment by ibmmqmet** [comment]
close for inactivity
