### ISSUE TITLE
User identification compatibility mode

### ISSUE THREAD

**Issue by kingdk** [ibm-messaging/mq-mqi-nodejs#68]
I have everything installed and working but am having trouble connecting to an MQ server running an old version of MQ. When using tools like "IBM MQ Explorer" or "MQ visual edit" to get a connection you need to select "USER Identification Compatibility Mode" to make a connection. MQ visual edit explains the option as "Retain the behavior of sending the UserId and password in the RemoteUserId and RemotePassword fields of the MQCD structure as done in releases prior to IBM MQ V8"

Does IBMMQ support this? is there a setting or parameter to set?
Thanks in advance

**Comment by ibmmqmet** [comment]
This package has not exposed those particular fields from the MQCD structure. Outside of Java programs, they would usually have been set by a security exit as they would then get validated by a corresponding SVRCONN security exit at the queue manager side. 

Since you don't say what kind of problem you're having, it's hard to know if that old authentication approach is what's going wrong.

**Comment by kingdk** [comment]
The problem I'm having is "MQ call failed in CONNX: MQCC = MQCC_FAILED [2] MQRC = MQRC_NOT_AUTHORIZED [2035]". This occurs when running your sample code "amqsconn.js". This is the same message received when using MQ visual Edit when the "USER Identification Compatibility Mode" is not selected.

Is there any way to hard code into your libraries values for the RemoteUserId and RemotePassword fields? I note inside of mqcd.js in the lib directory 2 lines of code:
  u.setMQIString(cd.RemoteUserIdentifier , "");
  u.setMQIString(cd.RemotePassword       , "");
These fields seem to be known but just ignored by your libraries.

Any help or advice would be very much appreciated.

**Comment by ibmmqmet** [comment]
I looked into it, and it is not possible to do this. Or rather, doing that does not have the desired effect. 

The "compatibility mode" is not available via the C client interface. For programs built on the C libraries, setting non-default userids outside of the MQCSP structure can only be done via a channel security exit or something on the SVRCONN definition (chlauth rules, explicit MCAUSER etc).
For Java programs, the JMS `connectionFactory.connect(user,pass)` method required ids to be sent, and pre-V8 it was done by internally emulating a channel exit - the compat mode option was then introduced to preserve that behaviour where required.

(The comment that Visual Edit gives about the fields is not really accurate - while those fields are the ones seen by a server-side authentication exit, they are not set that way by the client.)

**Comment by kingdk** [comment]
So, does what you say rule out the use of your IBMMQ node package to interface with an MQ server that requires the "compatibility mode"? or can it be made to work with a "channel security exit"? and if so are we talking about:

https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.0.0/com.ibm.mq.sec.doc/q114370_.htm

or something else?

Sorry if these seem like silly questions, I am a node developer who is completely new to MQ.

**Comment by ibmmqmet** [comment]
How do other C-based programs connect to your queue manager? Are they using a security exit? Does the SVRCONN on the qmgr have a security exit to do the authentication? It's certainly possible to use security exits with this package, but that's something your MQ administrator ought to be aware of and informing you about. 

The mqccred exit is anc example of a channel security exit, but it is designed to work with the MQCSP mechanism - it would not help if you've got a SVRCONN exit that's expecting particular information or formats.

**Comment by kingdk** [comment]
We are building a SAS product for clients who interact with a third-party's MQ server (to my knowledge, no one is using the C libraries, I think they all use JAVA). I don't have easy access to third-party MQ admin just a set of client credentials. I note that when using "IBM MQ Explorer" and "MQ visual edit" I don't need access to an MQ admin to access the queues. This seems like a known way of accessing MQ servers (however dated).

It is sounding as though the current C libraries do not allow access to older servers running with compatibility mode.

Thank you for your help.

**Comment by ibmmqmet** [comment]
If they really are running a security exit on the queue manager, those are usually developed in pairs, so I would expect a client-side security exit to be available from the queue manager adminstrator even if it's not used for any of their other applications. 

If they are not running a security exit, then there's no authentication going on, and the Java programs are simply asserting a userid. That is not possible from C clients - the program must be run under the username expected at the server or a different approach needs to be taken for controlling the username.

The "compatibility mode" flag is something applicable and internal to the Java client. It's not something recognised as an option by the server. 

Just about all queue managers that support ONLY exit-based authentication are out of support now. Anyone still running such a server is also running a risk. And while it's possible to continue to use those exits in current versions, MQCSP has been supported for authentication since V8. 

There are alternative approaches for getting a different userid into a qmgr without an exit or MQCSP structure but those require administrative changes on the queue manager. For example, requiring the client to use a specific TLS certificate and then using the SSLPEER attribute on the SVRCONN to approve the connection, and the MCAUSER attribute on that channel to assign a local userid may be suitably secure. CHLAUTH rules for more flexible mapping were added in V7.1 so there's been plenty of time to adopt those.
