### ISSUE TITLE
Getting CONNX: MQRC_ENVIRONMENT_ERROR(2012) during uploading IBMMQ node.js application on pivotal cloud foundry

### ISSUE THREAD

**Issue by shaileshyadav** [ibm-messaging/mq-mqi-nodejs#69]
Getting CONNX: MQRC_ENVIRONMENT_ERROR(2012) during uploading IBMMQ node.js application on pivotal cloud foundry. 
Is there compatibility issue with PCF(pivotal cloud foundry).

**Comment by ibmmqmet** [comment]
Someone recently reported this error code in a completely different environment because they had not correctly copied/installed the whole of the MQ client library to their container. In particular they were missing the ccsid.tbl and ccsid_part2.tbl files which in a Node.js app will probably be installed by the postinstall.js script into node_modules/ibmmq/redist/lib. Or installed elsewhere on your system if you've done a real rpm/deb install.

**Comment by ibmmqmet** [comment]
closed for inactivity after answer given
