### ISSUE TITLE
md.CorrelId changes with parallel messages processing

### ISSUE THREAD

**Issue by freerider7777** [ibm-messaging/mq-mqi-nodejs#74]
- mq-mqi-nodejs version 0.9.8
    mq.Get(queueGetConnection, mqmd, gmo, function (err, hObj, gmo, md, buf) {
      try {
        // mq.GetSync(queueGetConnection, mqmd, gmo, buf, function (err, len) {
        if (err) {
          if (err.mqrc == MQC.MQRC_NO_MSG_AVAILABLE) {
             logger.debug("no more messages");
          } else {
            mq.GetDone(hObj);
            cleanup();
          }
          ok = false;
        } else {
          let received = '';
         // save to local variable:
         const receivedCorrelId = md.CorrelId;

         // const receivedCorrelId = Buffer.from(`${md.CorrelId}`);  // workaround :)

// mnemonically - some async task:
http.get(...).then(response =>  {
  // PROBLEM:
  console.log(`correlId ${receivedCorrelId}`); // Here receivedCorrelId may change, if other message has been received during async call with Other CorrelId
} );

**Comment by ibmmqmet** [comment]
If I understand the question correctly, this is to be expected. The MQMD is reused on each iteration. The documentation for the Get() function does state that message data needs to be copied as the buffer can be overwritten by subsequent messages - the same is true of the MQMD. 

The "next" message will be retrieved after your callback has completed, and the MQMD can be reused at that point. The problem is that your http.get block is being scheduled for later execution, so as far as MQ is concerned, your callback function has completed. You would see this if you had a callback looking like

```
getCB(...) {
  console.log("1")
  http.get(url,response=>{console.log("2")});
  console.log("3")
}
```
The output will often have the "3" appearing before the "2".

I'll look at adding more notes about this into the JSDoc for the Get() function, but the solution is essentially as you have found - take a copy of things you want to use asynchronously before the callback function completes.

Part of the reason for this behaviour is to reduce the chance of leaks, if the MQ code were to create new MQMDs on each iteration, with no control of when they get freed.

**Comment by freerider7777** [comment]
Thanks for the answer, I migrated from version 0.92 to 0.98 and it stopped working :) I understand the flow (1 -> 3 -> 2), in js local variables usually keep the value, but here it is a mutable buffer.
Your reasoning is good - reducing chance of leak. I just wrote this issue to point to possible problems.
The library is great - help us a lot! :)
