### ISSUE TITLE
Create Topic Example

### ISSUE THREAD

**Issue by clearly** [ibm-messaging/mq-mqi-nodejs#77]
I'm new to MQ, been using cloud native stuff for a while. Wanted to see if there was an isolated example of creating a topic using this API.

**Comment by ibmmqmet** [comment]
What do you mean by "creating a topic"? If you simply mean to publish or subscribe to a topic, then there are samples amqspub/amqssub in here. See also [further samples here](https://github.com/ibm-messaging/mq-dev-patterns/). There is no requirement to actually define a specific topic string before using it, although there may be authorisations that you need in order to use a particular topic. 

If you truly mean creation of a topic object - ie the [DEFINE TOPIC](https://www.ibm.com/support/knowledgecenter/en/SSFKSJ_9.1.0/com.ibm.mq.ref.adm.doc/q085770_.htm) administrative command -  then that would be done via a PCF operation or by sending corresponding REST commands to a web server. I've not provided PCF generation or parsing samples in this repository; that's a much more advanced subject. REST operations are also outside the scope of this particular repository but they are fully documented in the knowledge center.

**Comment by clearly** [comment]
Thank you for the info! That is exactly the info I was looking for (2nd paragraph)
