### ISSUE TITLE
Redist 9.1.3.0 is removed and so builds are failing.

### ISSUE THREAD

**Issue by gaurang171** [ibm-messaging/mq-mqi-nodejs#97]
Please include the following information in your ticket.

- ibmmq@0.9.8
- A small code sample that demonstrates the issue.

Recently few redist files are deleted and due to that installation is failing with the following error. Is it possible to put the file back?

Downloading IBM MQ Redistributable C Client runtime libraries - version 9.1.3.0
Getting https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/messaging/mqdev/redist/9.1.3.0-IBM-MQC-Redist-LinuxX64.tar.gz
Error occurred downloading IBM MQ Redistributable C Client: 'Request Failed.

**Comment by ibmmqmet** [comment]
IBM's policy is to remove downloads of out-of-support versions wherever possible. So that's why the 9.1.3 package has been deleted. The 9.1.4 level has also gone from that site and other download locations.

If you move to a newer level of this package, then you'd pick up references to the 9.1.5 or 9.2.0 client. Alternatively, you can make use of the MQIJS_* environment variables to say that the download should even not be attempted, and instead to use a copy of older client libraries that you have kept and unpacked yourself.
